### ISSUE TITLE
Regexp based string generator

### ISSUE THREAD

**Issue by phadej** [jsverify/jsverify#19]

**Comment by taylor1791** [comment]
In my opinion, this is one of the only things missing in jsverify that its competitors has. [This](https://github.com/mukeshsoni/jssmartcheck/blob/master/src/generators/string.js#L82) is one example. Where is this feature at on your list of priorities?

**Comment by phadej** [comment]
Not very high, as I didn't personally needed it. Maybe I can take a look at this too, if there's real need.

**Comment by phadej** [comment]
Or actually I'd prefer a pull request.

**Comment by taylor1791** [comment]
I started on the pull request and quickly realized I don't really understand the way the library is structured. First, I apologize if I use the wrong lexicon. You should be able to see the [WIP](https://github.com/jsverify/jsverify/compare/master...taylor1791:master). I started working on the matchstring arbitrary and wrote a simple test that should fail. It does fail, but I get something I don't know how to fix (see stack track below). If it is easy for you to diagnose can you point me in the right direction. In addition, can you review what I started and tell me if I am on the right track? 
```
$ node_modules/.bin/mocha

  primitive arbitraries
    matchstring
      1) generates string

  0 passing (8ms)
  1 failing

  1) primitive arbitraries matchstring generates string:

      AssertionError: shrinkTuple needs > 0 values
      + expected - actual

      -false
      +true

      at Object.shrinkTuple [as tuple] (lib/shrink.js:156:3)
      at shrinkResult (lib/jsverify.js:135:25)
      at lib/jsverify.js:218:14
      at Object.bind (lib/functor.js:63:12)
      at test (lib/jsverify.js:197:20)
      at lib/jsverify.js:224:13
      at loop (lib/jsverify.js:298:26)
      at check (lib/jsverify.js:314:34)
      at Object.checkThrow [as assert] (lib/jsverify.js:336:34)
      at Context.<anonymous> (test/arbitrary.js:201:11)
```

**Comment by phadej** [comment]
Add `show: show.def` to an object you `arbitrary.bless`.

**Comment by taylor1791** [comment]
I have been working on this and I am on the final stretch. I came to the realization that in order for this to be efficient, we need to be able to generate from a discontinuous range. I don't think that there is an efficient way to do this in the existing library. Please correct me if I am wrong. 

I was planning on using [discontinuous-range](https://www.npmjs.com/package/discontinuous-range) to do the heavy lifting. Do you want this functionality exposed via the public API? Does something like this work?

    jsc.integerRange([[1, 10], [30, 40]], [[5,35]); // A generator with the values in the range [1,4] ∪ [36, 40]

The first parameter is the ranges to include and the second is the ranges to exclude. (excluding has higher priority than inclusion).

What do you think?

**Comment by phadej** [comment]
I was trying to keep jsverify lib as dependency free as possible (all dependencies so far are small libs I made specially for jsverify). I have to evaluate `discontinuous-range` properly. dtudury activity on github is a bit "non-existing" atm :(

The union part of `jsc.integerRange` could be done from `jsc.sum` and `jsc.integer` (as the latter supports continuos range). `jsc.sum` is not yet released, but it is in master.

If I interpret right, `discontinuous-range` internal structure is union of continuous ranges, so you don't need to do filtering of arbitraries. Which is great.

**Comment by phadej** [comment]
Ah, and `jsc.integerRange` can be public arbitrary. Why not.

**Comment by phadej** [comment]
And one more thing, what you think: if I setup and `jsverify-contrib` repository soon :tm:, would it be ok for you to have this regexp functionality there, and not in the "core"? Contrib could be "sloppier" with letting dependencies in, for example

**Comment by taylor1791** [comment]
I personally don't have any problem with it being in jsverify-contrib. If I manage to not need `discontinous-range` would you still want it in `jsverify-contrib`? Based on your suggestions, I am going to try to use `jsc.sum` and `jsc.integer` in lieu of  `discontinuous-range`. If that doens't work I can write a lighter version of `discontinuous-range`. Either way I will make separate merge requests. The first will be `jsc.integerRange`, followed by `jsc.matchstring` to the repository of your choice.

**Comment by taylor1791** [comment]
I just read the source for the `jsc.sum` and I don't think it will work because it generates uniformly over each adden. Take for example the range `[1, 11-12]`. `P(1)=0.5` and `P(11)=0.25`. `jsc.integerRange` needs to be `P(1)=P(11)=P(12)`. I'll work on a lighter version of `discontinuous-range` to remove the dependency.

**Comment by StoneCypher** [comment]
you just want something that has an equal likelihood of sampling any integer from a group of ranges?

roughly

```javascript
var total = ranges.foldl(0, (R,Acc) => Acc+(R.hi - R.lo + 1)),
      urand = Math.floor(Math.random() * total),
      cdown = urand,
      i     = 0;

while (cdown -= ranges[i++].hi > 0) {}
return ranges[i].lo - urand;
```

**Comment by taylor1791** [comment]
@StoneCypher That is the algorithm that I would implement. But please forgive me, but how did you get `ranges` out of `jsc`?

I just trying to say that I don't think `jsc.sum` is sufficient and we need that algorithm and some work to create the data structure `range`.

Did I miss something?

**Comment by StoneCypher** [comment]
i didn't get anything out of anywhere.  i just wrote a randomness seeking thing off of the top of my head.

**Comment by nicenemo** [comment]
Now Wrapping RandExp in a generator. Works for me.
