### ISSUE TITLE
Better error reporting / logging with properties that failed

### ISSUE THREAD

**Issue by puneetar** [jsverify/jsverify#234]
I am using this to test output of functions with different inputs. JsVerify provides me a counter example but does not provide the actual property value that it failed on.

example: 
```
function doSomething(a) {
  return a+2;
}

var testSomething =
  jsc.forall("nat", function (a) {
    return doSomething(a) === a+1;
  });

jsc.assert(testSomething);	  
```

It would fail with the error msg : 
`//Error: Failed after 49 tests and 1 shrinks. rngState: 074e9b5f037a8c21d6; Counterexample: 1;`

Instead it would be helpful to see what was the actual and expected values, something like : 
```
//Error: Failed after 49 tests and 1 shrinks. rngState: 074e9b5f037a8c21d6; Counterexample: 1;
// Actual : 3 , Expected : 2
```

For me it helps in writing complex test cases based on generative inputs.

**Comment by StoneCypher** [comment]
isn't the counterexample the thing you're asking for

**Comment by phadej** [comment]
```js
> function counterexample(cond, msg) { if (cond) { return true; } else { throw new Error(msg); } }
undefined
> jsc.checkForall("nat", "nat", function(x, y) { var lhs = x - y; var rhs = y - x; return counterexample(x === y, x + " =/= " + y); });
Failed after 1 tests and 3 shrinks. rngState: 0b5f2c14ad9e068b37; Counterexample: 0; 1; Exception: 0 =/= 1
Stack trace: Error: 0 =/= 1
    at counterexample (repl:1:99)
    at repl:1:89
    at Object.bind (/home/ogre/Documents/javascript/jsverify/lib/functor.js:48:11)
    at test (/home/ogre/Documents/javascript/jsverify/lib/jsverify.js:212:20)
    at /home/ogre/Documents/javascript/jsverify/lib/jsverify.js:151:13
    at Cons.consFold [as fold] (/home/ogre/Documents/javascript/jsverify/node_modules/lazy-seq/index.js:225:10)
    at Object.fold (/home/ogre/Documents/javascript/jsverify/node_modules/lazy-seq/index.js:440:17)
    at shrinkResult (/home/ogre/Documents/javascript/jsverify/lib/jsverify.js:150:25)
    at /home/ogre/Documents/javascript/jsverify/lib/jsverify.js:233:16
    at Object.bind (/home/ogre/Documents/javascript/jsverify/lib/functor.js:63:12) [ 0, 1 ]
{ counterexample: [ 0, 1 ],
  counterexamplestr: '0; 1',
  shrinks: 3,
  exc: 
   Error: 0 =/= 1
       at counterexample (repl:1:99)
       at repl:1:89
       at Object.bind (/home/ogre/Documents/javascript/jsverify/lib/functor.js:48:11)
       at test (/home/ogre/Documents/javascript/jsverify/lib/jsverify.js:212:20)
       at /home/ogre/Documents/javascript/jsverify/lib/jsverify.js:151:13
       at Cons.consFold [as fold] (/home/ogre/Documents/javascript/jsverify/node_modules/lazy-seq/index.js:225:10)
       at Object.fold (/home/ogre/Documents/javascript/jsverify/node_modules/lazy-seq/index.js:440:17)
       at shrinkResult (/home/ogre/Documents/javascript/jsverify/lib/jsverify.js:150:25)
       at /home/ogre/Documents/javascript/jsverify/lib/jsverify.js:233:16
       at Object.bind (/home/ogre/Documents/javascript/jsverify/lib/functor.js:63:12),
  tests: 1,
  rngState: '0b5f2c14ad9e068b37' }
```

Would that solve @puneetar's problem?

**Comment by phadej** [comment]
Actually! If you return string:

```js
> function counterexample(cond, msg) { if (cond) { return true; } else { return msg; } }
undefined
> jsc.checkForall("nat", "nat", function(x, y) { var lhs = x - y; var rhs = y - x; return counterexample(x === y, x + " =/= " + y); });
Failed after 1 tests and 9 shrinks. rngState: 840d2f49a5c3617e8b; Counterexample: 0; 1; Error: 0 =/= 1 [ 0, 1 ]
{ counterexample: [ 0, 1 ],
  counterexamplestr: '0; 1',
  shrinks: 9,
  exc: '0 =/= 1',
  tests: 1,
  rngState: '840d2f49a5c3617e8b' }
```

**Comment by phadej** [comment]
... and without `counterexample`:

```js
> jsc.checkForall("nat", "nat", function(x, y) { var lhs = x - y; var rhs = y - x; return lhs === rhs || lhs + " =/= " + rhs });
Failed after 1 tests and 4 shrinks. rngState: 8647f389ac0de2b651; Counterexample: 0; 1; Error: -1 =/= 1 [ 0, 1 ]
{ counterexample: [ 0, 1 ],
  counterexamplestr: '0; 1',
  shrinks: 4,
  exc: '-1 =/= 1',
  tests: 1,
  rngState: '8647f389ac0de2b651' }
```

If someone could add that example to the documentation, I'd appreciate!

**Comment by puneetar** [comment]
@phadej thanks, I think you last solution "without `conterexample`" works for simple cases when there is only one assertion to be made. 

It gets tricky to generate string representation when there are multiple assertions to be made .. 
Consider where we have `lhs1 === rhs1`  and `lhs2 === rhs2`  and ...

**Comment by phadej** [comment]
@puneetar why would you have

`lhs1 === rhs1 && lhs2 === rhs2`, and not two properties?

Anyhow, if you need something complicated, write a helper function.

**Comment by puneetar** [comment]
yup that makes sense 👍
