### ISSUE TITLE
How do I get the counterexample generated by `smap` in a failure message?

### ISSUE THREAD

**Issue by jergason** [jsverify/jsverify#252]
How do I get the counterexample generated by `smap` when a test fails?

Here is a simplified example of a test that generates an array with a duplicate value.

```javascript
it.only("works kinda", () => {
  const numbers = jsc
    .nearray(jsc.integer())
    .smap(a => (a.push(a[0]), a), a => (a.pop(), a));
  jsc.assertForall(numbers, a => !isUnique(a));
});

function isUnique(a) {
  // NOTE: obviously fake implementation here
  return true;
}

```

This fails because the implementation is broken, but here is the output I get:

```bash
$ mocha */**test.js


  1) works kinda

  0 passing (8ms)
  1 failing

  1) works kinda:
     Error: Failed after 1 tests and 1 shrinks. rngState: 00f936540782abedc1; Counterexample: [-10]; 
      at node_modules/jsverify/lib/jsverify.js:360:15
      at Object.map (node_modules/jsverify/lib/functor.js:35:12)
      at checkThrow (node_modules/jsverify/lib/jsverify.js:354:30)
      at Object.assertForall (node_modules/jsverify/lib/jsverify.js:485:10)
      at Context.it.only (ch-07/test.js:106:7)
```

The call to `smap` means the data that caused the test to fail looks like this: `[-10, -10]`. However, the counterexample only lists the data before `smap`. How do I get the counterexample to print out the data that actually caused the test to fail?

I know I can just make a helper to capture the data that caused the failure myself, but is there a way to get this to happen automatically?

**Comment by phadej** [comment]
Try

```haskell
function isUnique(a) {
  return a.toString(); // only `true` is considered "property holds".
}
```

**Comment by glebec** [comment]
Oh wow, if this is in the docs I did not realize it – if you don't return `true` or a Promise for `true`, JSVerify includes whatever you return in the error message.

```js
jsc.assert(jsc.forall('[integer]', (arr) => {
    return isOrdered(sort(arr)) ? true : sort(arr)
}))
```

```
Error: Failed after 3 tests and 10 shrinks. rngState: 058329dab764e510cf; Counterexample: [2, 10]; Error: 10,2
```

The key part there is `Error: 10,2` which doesn't appear if you merely return `false`. This is some pretty subtle behavior, will check if it is mentioned somewhere… if not I think it should be made clearer.
