### ISSUE TITLE
Issue in assert while running tests for async functions

### ISSUE THREAD

**Issue by pntripathi9417** [jsverify/jsverify#275]
I have written the following test to test I/O operations to MongoDB.

```
import _ from 'lodash';
import jsc from 'jsverify';
import mongoose from 'mongoose';
import MongodbMemoryServer from 'mongodb-memory-server';

import Mongo from '../Mongo';

jasmine.DEFAULT_TIMEOUT_INTERVAL = 60000;

let mongoServer;
const opts = { useNewUrlParser: true };

const {
  forall,
  record,
  nestring,
  check,
  assert
} = jsc;

const options = {
  tests: 100,
  quite: false,
  size: 50,
  // rngState: '0021a649dfcb038e57',
};

beforeAll(async () => {
  mongoServer = new MongodbMemoryServer();
  const mongoUri = await mongoServer.getConnectionString();
  await mongoose.connect(mongoUri, opts, (err) => {
    if (err) console.error(err);
  });
});

afterAll(() => {
  mongoose.disconnect();
  mongoServer.stop();
});

/**
 * @test {Mongo}
 */
describe('Mongo', () => {
  it('should create proper mongoose instance', (done) => {
    const schema = {
      username: {
        type: String
      }
    };

    class User extends Mongo {
      constructor() {
        super({ schema });
      }
    }
    const userInstance = new User();

    const arbUser = record({
      username: nestring
    });

    const property = forall(
      arbUser,
      user => userInstance.createDoc({ data: user })
        .then(doc => _.isEqual(user.username, doc.username))
    );

    assert(property, options)
      .then((result) => {
        if (result) return done();
        return done('error');
      })
      .catch(error => done(error));
  });
});
```
If I use `assert` I get following response while running test:

```
 FAIL  dist/adapters/__tests__/Mongo.spec.js
  Mongo
    ✕ should create proper mongoose instance (115ms)

  ● Mongo › should create proper mongoose instance

    Failed: "error."

      160 |     _jsverify2.default.assert(property, options).then(function (result) {
      161 |       if (result) return done();
    > 162 |       return done('error');
          |              ^
      163 |     }).catch(function (error) {
      164 |       return done(error);
      165 |     });

      at Env.fail (node_modules/jest-jasmine2/build/jasmine/Env.js:540:34)
      at dist/adapters/__tests__/Mongo.spec.js:162:14

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    33.72 |    15.63 |    37.14 |    34.52 |                   |
 Mongo.js |    33.72 |    15.63 |    37.14 |    34.52 |... 15,516,520,527 |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.535s, estimated 3s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dbal@0.0.1 test: `jest --coverage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dbal@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

But as I start using `check` it works as expected with following output:

```
npm run test

> dbal@0.0.1 test /Users/pragyan/Projects/vadelabs/server/packages/dbal
> jest --coverage

 PASS  dist/adapters/__tests__/Mongo.spec.js
  Mongo
    ✓ should create proper mongoose instance (125ms)

  console.info node_modules/jsverify/lib/jsverify.js:334
    OK, passed 100 tests

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    33.72 |    15.63 |    37.14 |    34.52 |                   |
 Mongo.js |    33.72 |    15.63 |    37.14 |    34.52 |... 15,516,520,527 |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.612s
Ran all test suites.
```

**Comment by qlonik** [comment]
Hey, it appears that assert returns either Promise which rejects, if the property fails, or Promise which resolves with undefined, when it succeeds. 

In your example, after assert is done, you are calling `done()` without error when result is truthy, but it will never be truthy in case of successful test.

It should be:
```js
assert(property, options)
  .then(() => done())
  .catch(error => done(error));
```
