### ISSUE TITLE
jsc.suchthat doesn't work with pairs

### ISSUE THREAD

**Issue by cipix2000** [jsverify/jsverify#99]
The following test

````javascript
    it("shrinks a pair so predicate is true for all shrinked values still", function () {
      var smallAndBigPair = jsc.suchthat(jsc.pair(jsc.nat()), function (pair) {
        return pair[0] <= pair[1];
      });

      checkShrink([0, 0], jsc.forall(smallAndBigPair, function (pair) {
        return pair[0] < pair[1];
      }), 100);
    });
````
fails with: 

 1) shrink suchthat shrinks a pair so predicate is true for all shrinked values still:
     TypeError: Object nil has no method 'filter'
      at shrink (lib/suchthat.js:43:28)
      at lib/shrink.js:28:12
      at Object.curriedNInstance [as curried2] (lib/utils.js:102:14)
      at Object.shrinkTuple [as tuple] (lib/shrink.js:147:16)
      at shrinkResult (lib/jsverify.js:126:25)
      at lib/jsverify.js:208:14
      at Object.bind (lib/functor.js:55:12)
      at test (lib/jsverify.js:187:20)
      at lib/jsverify.js:214:13
      at loop (lib/jsverify.js:276:13)
      at Object.check (lib/jsverify.js:291:22)
      at checkShrink (test/shrink.js:15:17)
      at Context.<anonymous> (test/shrink.js:95:7)

**Comment by phadej** [comment]
This issue should be fixed (at least the test case passes). @cipix2000, could you verify?

**Comment by cipix2000** [comment]
Thank you @phadej, it seems to be fixed. 

I really like what you are doing with jsverify ! keep the good work.

**Comment by phadej** [comment]
Thanks to you for spotting the bug!
